In [1]:
import numpy as np
import pandas as pd

In [2]:
#1
monday = pd.Series({'Alice' : 8, 'Bob' : 6, 'David' : 7})
monday

Alice    8
Bob      6
David    7
dtype: int64

In [16]:
#1
tuesday = pd.Series ({'Bob' : 8, 'Carol' : 5, 'David' : 6})
tuesday

Bob      8
Carol    5
David    6
dtype: int64

In [17]:
#1
wednesday = pd.Series ({'Alice' : 7, 'Carol' : 8, 'David' : 5})
wednesday

Alice    7
Carol    8
David    5
dtype: int64

In [20]:
#2
weekly_workers = monday.add(tuesday,fill_value = 0).add(wednesday,fill_value = 0)
weekly_workers

Alice    15.0
Bob      14.0
Carol    13.0
David    18.0
dtype: float64

In [32]:
#3
total_hours = max(weekly_workers.keys())
total_hours

'David'

In [39]:
#Q4 option 1
data = {' Workers Name' : ['Alice','Bob','Carol','David'],'Total Hours' : [15,14,13,18]}
Q = pd.DataFrame (data)
Q

   Workers Name  Total Hours
0         Alice           15
1           Bob           14
2         Carol           13
3         David           18

In [40]:
#Q4 option 2
data = [['Alice',15],['Bob',14],['carol',13],['David',18]]
working_hours = pd.DataFrame (data, columns = ['Name','Hours'])
working_hours

    Name  Hours
0  Alice     15
1    Bob     14
2  carol     13
3  David     18